from . import ach, \
              autojoin, \
              brfares, \
              complete, \
              crypto, \
              decide, \
              echo, \
              freebase, \
              github, \
              google, \
              grep, \
              hash, \
              help, \
              heroku, \
              http, \
              humble, \
              instagram, \
              isup, \
              joke, \
              news, \
              nicebot, \
              oeis, \
              pastebin, \
              remind, \
              seen, \
              sendto, \
              sentiments, \
              sprunge, \
              steam, \
              tee, \
              trains, \
              translate, \
              twitter, \
              unicode, \
              url_titles, \
              vimeo, \
              wait, \
              wolfram, \
              xkcd, \
              youtube
